# Site settings
title: AydenKoans
email: jessyplemire@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Maths, physics, Rust dev and all these other things.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jadpole.github.io" # the base hostname & protocol for your site
# witter_username: jekyllrb
github_username:  jadpole
twitter_username: jadpole

gems:
  - jekyll-redirect-from

# Build settings
kramdown:
  input: GFM

permalink: "/:categories/:title"
